baseURL = "https://knarfamlap.github.io/"
languageCode = "en-us"
title = "Frank Palma Gomez"
theme = "archie"
copyright = "© knarfamlap"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
mode="dark"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/knarfamlap/"

[[menu.main]]
name = "Casa"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4