baseURL = "https://knarfamlap.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"

pygmentsCodefences = true
pygmentsStyle = "colorful"

paginate = 20

title = "Frank Palma Gomez"
theme = "flamingo"
[markup.goldmark.renderer]
unsafe = true

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true


[params]
  author = "Frank Palma Gomez"
  sitename = "Frank Palma's blog"
  github = "https://github.com/knarfamlap"
  favicon = "/images/favicon.ico"
  resume = "https://github.com/knarfamlap"



# Projects list

[[params.projects]]
  name = "Naive Bayes From Scratch"
  description = "Simple naive bayes implementation that works in the web."
  demoLink = ""
  sourceLink = ""

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
