baseURL = "https://knarfamlap.github.io/"
defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en"
paginate = 6
theme = "hugo-theme-texify"
title = "Frank Palma Gomez"

disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true

[author]
name = "Frank Palma Gomez"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "posts"
  name = "Post"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  identifier = "Papers"
  name = "Papers"
  url = "/papers/"
  weight = 3

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 4

[params]
  custom_css = []
  description = "an example site for hugo theme TeXify"
  enable_mathjax = true
  footnote = "Follow me on <a class=link href=https://github.com/knarfamlap>GitHub</a>"
  keywords = ["hugo", "latex", "theme"]